### ISSUE TITLE
Secure Pairing with esphome ble_client

### ISSUE THREAD

**Issue by archef2000** [wifwucite/esphome-ble-controller#18]
# Secure PIN not displayed

Now that ESPHome supports secure PIN pairing i tried it but the connection is failing and the "server" is not displaying the pin.

config A:
```yaml
esphome:
  name: esp-a

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
api:
  ***
ota:
  ***
wifi:
  ***

captive_portal:

web_server:
  port: 80

external_components:
  - source: github://wifwucite/esphome-ble-controller

esp32_ble_controller:
  security_mode: secure
  on_show_pass_key:
  - logger.log:
      format: "pass key is %s"
      args: 'pass_key.c_str()'
  on_authentication_complete:
  - logger.log:
      format: "BLE authentication complete %d" # shows 1 on success, 0 on failure
      args: 'success'
  maintenance: false
  on_connected:
    - logger.log: "Connected."
  on_disconnected:
    - logger.log: "Disconnected."
```
config B:
```yaml
esphome:
  name: esp-b

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
api:
  ***
ota:
  ***
wifi:
  ***

captive_portal:

web_server:
  port: 80

number:
  - platform: template
    name: "BLE Passkey"
    id: ble_passkey
    step: 1
    min_value: 000000
    max_value: 999999
    optimistic: True
    on_value:
      then:
        - ble_client.passkey_reply:
            id: ble_itag
            passkey: !lambda "return (int)id(ble_passkey).state;"

esp32_ble_tracker:
  scan_parameters:
    interval: 10s
    continuous: true
ble_client:
  - mac_address: EC:62:60:9C:9E:9A
    id: ble_itag
    on_passkey_request:
      then:
        - logger.log:
            format: "Waiting on passkey"
    on_passkey_notification:
      then:
        - logger.log:
            format: "Enter this passkey on your BLE device: %06d"
            args: [ passkey ]
    on_numeric_comparison_request:
      then:
        - logger.log:
            format: "Compare this passkey with the one on your BLE device: %06d"
            args: [ passkey ]
        - ble_client.numeric_comparison_reply:
            id: ble_itag
            accept: True
    on_connect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Connected to BLE device");
    on_disconnect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Disconnected from BLE device");

```

log A:
```
[D]	[esp32_ble_controller:491] BLE server - connected
[D]	[main:274] Connected.
[D]	[esp32_ble_controller:467] BLE authentication - failed
[D]	[main:268] BLE authentication complete 0
[D]	[esp32_ble_controller:499] BLE server - disconnected
[D]	[main:280] Disconnected.
```

log B:
```
[D]	[esp32_ble_tracker:245]	Starting scan...
[D]	[esp32_ble_client:048] [0] [EC:62:60:9C:9E:9A] Found device
[D]	[esp32_ble_tracker:213]	Pausing scan to make connection...
[I]	[esp32_ble_client:064] [0] [EC:62:60:9C:9E:9A] 0x00 Attempting BLE connection
[I]	[esp32_ble_client:265] [0] [EC:62:60:9C:9E:9A] auth complete. remote BD_ADDR: ec62609c9e9a
[E]	[esp32_ble_client:268] [0] [EC:62:60:9C:9E:9A] auth fail reason = 0x66
[D]	[ble_client_lambda:166]	Disconnected from BLE device
[D]	[esp32_ble_tracker:245]	Starting scan...
```

**Comment by wifwucite** [comment]
The problem is that ESPHome‘s ble_client component does not support secure pairing so far. This also mentioned in the [documentation](https://github.com/wifwucite/esphome-ble-controller#switch-configuration-ble-client). Secure pairing works with mobile, tablets or pcs. Please file an enhancement request for ble_client.

**Comment by archef2000** [comment]
It has just changed in the official [DOCS](https://esphome.io/components/ble_client.html)

**Comment by wifwucite** [comment]
I will have a look.

**Comment by archef2000** [comment]
The docs have changed again you need to add:
[BLE Component](https://esphome.io/components/esp32_ble.html?highlight=esp32_ble)
```yaml
api:
  services:
    - service: passkey_reply
      variables:
        passkey: int
      then:
        - logger.log: "Authenticating with passkey"
        - ble_client.passkey_reply:
            id: my_ble_client
            passkey: !lambda return passkey;
    - service: numeric_comparison_reply
      variables:
        accept: bool
      then:
        - logger.log: "Authenticating with numeric comparison"
        - ble_client.numeric_comparison_reply:
            id: my_ble_client
            accept: !lambda return accept;

esp32_ble:
  io_capability: keyboard_display
```
