### ISSUE TITLE
So close ... how do I send commands over the command channel?

### ISSUE THREAD

**Issue by nabheet** [wifwucite/esphome-ble-controller#24]
I think I have tried really hard to find an example of how to send commands over the command channel. I don't think I understand BLE enough to even ask a sensible question. Can you please provide an example of sending commands over the command channel?

**Comment by nabheet** [comment]
just realized maybe it is a different service/characteristic?

**Comment by nabheet** [comment]
Here is my config. I would like to send the wifi enable/disable commands over BLE.

```
esphome:
  name: sunroom-bottom-end-stop
  friendly_name: sunroom-bottom-end-stop
  platformio_options:
    board_build.flash_mode: dio
    
esp32:
  variant: ESP32C3
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.86.63
    gateway: 192.168.86.1
    subnet: 255.255.255.0

  ap:
    ssid: "Sunroom-Bottom-End-Stop"
    password: !secret fallback_password

external_components:
  - source: github://wifwucite/esphome-ble-controller

binary_sensor:
  - platform: gpio
    name: Bottom End Stop
    id: bottom_end_stop
    internal: True
    pin:
      number: 07
      inverted: True
      mode:
        input: True
        pullup: True


sensor:
  - platform: adc
    name: "Battery voltage"
    id: battery_voltage
    pin: GPIO0
    accuracy_decimals: 2
    update_interval: 60s
    attenuation: auto
    filters:
      - multiply: 10.0

esp32_ble_controller:
  services:
    - service: "0000180F"
      characteristics:
        - characteristic: "00002A19"
          exposes: battery_voltage
    - service: "fc23b9ec-4b22-4356-abec-6083712765e3"
      characteristics:
        - characteristic: "4ef07259-6c07-4c95-a2a0-56072829e1ec"
          exposes: bottom_end_stop

  commands:
    - command: toggle-wifi
      description: Toggle Wifi
      on_execute:
        - if:
            condition: wifi.enabled
            then:
              - logger.log: "Wifi Disabled"
              - wifi.disable:
            else:
              - logger.log: "Wifi Enabled"
              - wifi.enable:

  security_mode: none

captive_portal:

```

@archef2000 any suggestions please?
