### ISSUE TITLE
Light component support

### ISSUE THREAD

**Issue by adlemx** [wifwucite/esphome-ble-controller#27]
Hi, i saw commented lines in the code for light control, why are they commented?
Is it possible to control lighting via ble?

**Comment by archef2000** [comment]
It is compatible: https://github.com/wifwucite/esphome-ble-controller?tab=readme-ov-file#light-configuration-ble-server

**Comment by adlemx** [comment]
Thanks, but I think this is a workaround. Light components have additional parameters, such as brightness, color, etc. Now I have implemented this through commands with arguments, but it seems more correct to me that this is done by a separate service with separate characteristics

**Comment by archef2000** [comment]
Oh ok maybe share your for someone that may need this if it is not too much work. The Problem would be the client side as you need to write to each chars and in the server side you need to define more chars.

**Comment by adlemx** [comment]
Yes, here is my workaround

```yaml
light:
  - platform: rgb
    name: "ESP - RGB"
    id: light_rgb
    red: output_R
    green: output_G
    blue: output_B
    
# ...outputs config...

esp32_ble_controller:
  - command: set-lamp
    description: Control RGB lamp state brightness and color
    on_execute:
    - lambda: |-
          bool state = arguments[0] == "on";
          auto call = id(light_rgb).turn_on();
          if (!state) {
          call = id(light_rgb).turn_off();
          }
          if (arguments.size() > 1) {
          int brightness = esphome::parse_number<int>(arguments[1].c_str()).value();
          call.set_brightness(brightness / 100.0);  // Assuming brightness is 0-100
          }
          if (arguments.size() > 4) {
          float r = esphome::parse_number<float>(arguments[2].c_str()).value();
          float g = esphome::parse_number<float>(arguments[3].c_str()).value();
          float b = esphome::parse_number<float>(arguments[4].c_str()).value();
          call.set_rgb(r, g, b);
          }
          if (arguments.size() > 5) {
          float ts = esphome::parse_number<int>(arguments[5].c_str()).value();
          call.set_transition_length(ts);
          }
          call.perform();
  - command: get-lamp
    description: Get lamp state
    on_execute:
    - ble_cmd.send_result:
        format: "lamp-state %d %f %f %f %f"
        args: 
          - 'id(light_rgb).current_values.is_on()'
          - 'id(light_rgb).current_values.get_brightness()'
          - 'id(light_rgb).current_values.get_red()'
          - 'id(light_rgb).current_values.get_green()'
          - 'id(light_rgb).current_values.get_blue()'
```
