### ISSUE TITLE
Is the esphome-ble-controller compatible with ESP32S3 WROOM1 AND Ios devices? 

### ISSUE THREAD

**Issue by Ghofranezirouh** [wifwucite/esphome-ble-controller#28]
Hi! Sorry for bothering you. I have written this YAML with your configuration options and ESP32. It works perfectly!

Now, I would like to add a display (Lilygo 4.7” screen) with an ESP32 S3 WROOM1. I want the display to show the updates, unfortunately, I can’t even connect it to the iOS device on the app.

### Here’s the YAML I used for ESP32:

```
esphome:
  name: freequency

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: VERY_VERBOSE

external_components:
  - source: github://wifwucite/esphome-ble-controller

binary_sensor:
  - platform: gpio
    pin: 34
    name: irsensor
    id: irsensor
    filters:
      - delayed_off: 100ms
      - delayed_on: 100ms
  - platform: gpio
    pin: 18
    name: endstop
    id: endstop
    filters:
      - delayed_off: 100ms
      - delayed_on: 100ms
switch:
  - platform: gpio
    pin: 17
    name: blue
    id: blue
    restore_mode: ALWAYS_OFF
  - platform: template
    id: virtualservomot
    turn_on_action:
      - logger.log: "virtualservomot ON"
      - servo.write:
          id: servomot
          level: 100%
    turn_off_action:
      - logger.log: "virtualservomot OFF"
      - servo.write:
          id: servomot
          level: 0%
          

servo:
  id: servomot
  output: servomotledcOutput
  auto_detach_time: 0s
  transition_length: 0s
  min_level: 2.5%
  idle_level: 7.5%
  max_level: 12.5%
output:
  platform: ledc
  id: servomotledcOutput
  pin: 27
  frequency: 50 Hz

esp32_ble_controller:
  security_mode: none
  maintenance: false
  on_connected:
    - then:
        - switch.turn_on: blue
        - delay: 5s
        - switch.turn_off: blue

  services:
  - service: "3e440001-f5bb-357d-719d-179272e4d4d9"
    characteristics:
      - characteristic: "3e440003-f5bb-357d-719d-179272e4d4d9"
        exposes: virtualservomot
      - characteristic: "3e440004-f5bb-357d-719d-179272e4d4d9"
        exposes: irsensor
      - characteristic: "3e440005-f5bb-357d-719d-179272e4d4d9"
        exposes: endstop
      # - characteristic: "3e440003-f5bb-357d-719d-179272e4d4d9"
      #   exposes: `blueled`
```

### For the ESP32S3, I added the following parameters:

```platformio_options:
  upload_speed: 921600
  monitor_speed: 115200
  board_build.mcu: esp32s3
  board_build.f_cpu: 240000000L
  board_build.arduino.memory_type: qspi_opi
  board_build.flash_size: 16MB
  board_build.flash_mode: qio
  board_build.flash_type: qspi
  board_build.psram_type: opi
  board_build.memory_type: qspi_opi
  board_build.boot_freq: 80m
  platform_packages:
    - "toolchain-riscv32-esp @8.4.0+2021r2-patch5"
  build_flags:
    - "-DBOARD_HAS_PSRAM"
    - "-DARDUINO_RUNNING_CORE=0"
    - "-DARDUINO_EVENT_RUNNING_CORE=0"
    - "-DARDUINO_USB_MODE=1"
    - "-DARDUINO_USB_CDC_ON_BOOT=1"

esp32:
  variant: esp32s3
  board: esp32-s3-devkitc-1

framework:
  type: arduino
  version: 2.0.3
  platform_version: 5.1.1
```

### I have tried the following: 
- Ensure the esp32s3 and board parameters are correctly set for the Lilygo 4.7" display.
- You might need to check if the BLE controller and GPIO pins conflict with the display's functionality.
- Check the version compatibility for the esp32-s3-devkitc-1 board with ESPHome and the display.

 Would you have any clue about what the issue might be? Thank you in advance for your help!
