### ISSUE TITLE
ModuleNotFoundError: No module named 'esphome.components.ble_controller'

### ISSUE THREAD

**Issue by bbrendon** [wifwucite/esphome-ble-controller#32]
Does this work with 2025.2.2?

I tried these two variations  to my sensor config file:
```
external_components:
  - source: github://wifwucite/esphome-ble-controller


external_components:
  source:
    type: git
    url: https://github.com/wifwucite/esphome-ble-controller.git
```
